Gem::Specification.new do |s|
	s.name        = 'self_generating_cli'
	s.version     = '0.0.0'
	s.date        = '2017-10-11'
	s.summary     = "A CLI that gets generated by yard code comments"
	s.description = "This an example of how you might build a CLI that gets generated by yard code comments"
	s.authors     = ["Brett Sykes"]
	s.email       = 'brettcsykes@gmail.com'
	s.homepage    = 'https://github.com/bretts/self_generating_cli.git'
	s.files       = Dir.glob("{lib}/**/*")
	s.executables = ["sgcli"]
	s.license     = 'MIT'

	s.add_development_dependency "bundler", "~> 1.15"
	s.add_development_dependency "rake", "~> 10.0"

	s.add_runtime_dependency 'yard', '~> 0.9'
end
